Pages/Admin.cshtml.cs
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Assignment.Pages
{
    [Authorize(Roles = "Admin")]
    public class AdminsModel : PageModel
	{
		private readonly AuthDbContext _context;

		public AdminsModel(AuthDbContext context)
		{
			_context = context;
		}
		public async Task<IActionResult> OnGet()
        {
			var user = _context.Users.ToList().Where(member => member.Email == (User.FindFirstValue(ClaimTypes.Email))).FirstOrDefault();
			_context.AuditLogs.Add(new AuditLog
			{
				UserId = user.Id,
				ActivityDetails = "Admin has viewed page.",
				Timestamp = DateTime.Now,
			});
			await _context.SaveChangesAsync();
			return Page();
		}
    }
}

Pages/ChangePassword.cshtml.cs
using Assignment.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using System.Web;

namespace Assignment.Pages
{
	[AutoValidateAntiforgeryToken]
	public class ChangePasswordModel : PageModel
	{
		[BindProperty]
		public string oldPassword { get; set; }
		[BindProperty]
		public string Password { get; set; }
		[BindProperty]
		public string confirmPassword { get; set; }
		private readonly AuthDbContext _context;
		private readonly IHttpContextAccessor _contextAccessor;
		private UserManager<ApplicationMember> _userManager { get; set; }
		private SignInManager<ApplicationMember> _signInManager { get; set; }
		private ILogger<ChangePasswordModel> _logger { get; set; }

		public ChangePasswordModel(AuthDbContext context, UserManager<ApplicationMember> userManager, SignInManager<ApplicationMember> signInManager, IHttpContextAccessor contextAccessor, ILogger<ChangePasswordModel> logger)
		{
			_context = context;
			_userManager = userManager;
			_signInManager = signInManager;
			_contextAccessor = contextAccessor;
			_logger = logger;
		}
		public IActionResult OnGet()
		{
			var email = _contextAccessor.HttpContext.Session.GetString("Email");
			if (email == null && User.FindFirstValue(ClaimTypes.Email) == null)
			{
				return RedirectToPage("Login");
			}
			return Page();
		}

		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
				var email = _contextAccessor.HttpContext.Session.GetString("Email");
				ApplicationMember user;
				if (email != null)
				{
					user = _context.Users.ToList().Where(member => member.Email == email).FirstOrDefault();
				}
				else
				{
					user = _context.Users.ToList().Where(member => member.Email == User.FindFirstValue(ClaimTypes.Email)).FirstOrDefault();
				}
				var passwordcheck = await _signInManager.CheckPasswordSignInAsync(user, Password, false);
				var oldpasswordcheck = await _signInManager.CheckPasswordSignInAsync(user, oldPassword, false);
				var passwordcheck2 = _userManager.PasswordHasher.VerifyHashedPassword(user, user.PasswordHashed2, Password);
				if (!oldpasswordcheck.Succeeded)
				{
					ModelState.AddModelError("", "Your password is wrong.");
				}
				else
				{
					if (user.MinimumPasswordAge > DateTime.Now)
					{
						ModelState.AddModelError("", "Password has been changed recently, please wait a day after you last changed it.");
					}
					else if (passwordcheck.Succeeded || passwordcheck2 != PasswordVerificationResult.Failed)
					{
						ModelState.AddModelError("", "Your password can't be the same as your previous 2.");
					}
					else if (Password != confirmPassword)
					{
						ModelState.AddModelError("", "Your password and confirm password aren't the same.");
					}
					else
					{
						var token = await _userManager.GeneratePasswordResetTokenAsync(user);
						user.PasswordHashed2 = user.PasswordHash;
						var result = await _userManager.ResetPasswordAsync(user, token, HttpUtility.HtmlEncode(Password));
						if (result.Succeeded)
						{
							_context.AuditLogs.Add(new AuditLog
							{
								UserId = user.Id,
								ActivityDetails = "User has changed their password.",
								Timestamp = DateTime.Now,
							});
							user.MinimumPasswordAge = DateTime.Now.AddDays(1);
							user.MaximumPasswordAge = DateTime.Now.AddDays(120);
							_contextAccessor.HttpContext.Session.Remove("Email");
							await _context.SaveChangesAsync();
							return RedirectToPage("Homepage");
						}
						foreach (var error in result.Errors)
						{
							ModelState.AddModelError("", error.Description);
						}
					}
				}
			}
			return Page();
		}
	}
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Assignment.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/ForgetPassword.cshtml.cs
using Assignment.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Assignment.Pages
{
	public class ForgetPasswordModel : PageModel
	{
		private readonly AuthDbContext _context;
		private readonly IHttpContextAccessor _contextAccessor;
		private readonly IEmailSender _emailSender;
		public ForgetPasswordModel(AuthDbContext context, IEmailSender emailSender, IHttpContextAccessor contextAccessor)
		{
			_context = context;
			_emailSender = emailSender;
			_contextAccessor = contextAccessor;
		}
		public async Task<IActionResult> OnGet()
        {
			var email = _contextAccessor.HttpContext.Session.GetString("Email");
			if (email == null)
			{
				return RedirectToPage("Login");
			}
			else
			{
				await _emailSender.SendEmailAsync(email, "Password Reset", "Click here to reset your password https://localhost:7278/ChangePassword");
				return Page();
			}
		}
    }
}

Pages/Homepage.cshtml.cs
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace Assignment.Pages
{
    [Authorize]
    public class HomepageModel : PageModel
    {

        private readonly AuthDbContext _context;
        private readonly ILogger<HomepageModel> _logger;
        private readonly SignInManager<ApplicationMember> _signInManager;

        public HomepageModel(AuthDbContext context, ILogger<HomepageModel> logger, SignInManager<ApplicationMember> signInManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
        }
        public IActionResult OnGet()
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return RedirectToPage("Login");
            }
            else
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("HiddenWow");

                List<ApplicationMember> members = _context.Users.ToList();
                var useremail = User.FindFirstValue(ClaimTypes.Email);
                var user = members.Where(member => member.Email == useremail).FirstOrDefault();
                ViewData["Email"] = user.Email;
                ViewData["DateOfBirth"] = user.DateOfBirth;
                ViewData["FirstName"] = user.FirstName;
                ViewData["LastName"] = user.LastName;
                ViewData["Gender"] = user.Gender;
                ViewData["NRIC"] = protector.Unprotect(user.NRIC);
                ViewData["WhoAmI"] = user.WhoAmI;
                ViewData["Resume"] = user.Resume;

                return Page();
            }
        }

        public IActionResult OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                _logger.LogInformation("heloo");
                return RedirectToPage("ChangePassword");
            }
            return Page();
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            var storedSessionId = HttpContext.Session.GetString("AuthToken");

            if (storedSessionId != Request.Cookies["AuthToken"])
            {
                return RedirectToPage("Login");

            }
            return Page();
        }
    }
}

Pages/Login.cshtml.cs
using Assignment.Models;
using Assignment.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;
using System.Web.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Diagnostics.Eventing.Reader;

namespace Assignment.Pages
{
	[AutoValidateAntiforgeryToken]
	public class LoginModel : PageModel
	{
		[BindProperty]
		public Login LModel { get; set; }
		private readonly SignInManager<ApplicationMember> signInManager;
		private readonly ILogger<LoginModel> _logger;
		private readonly IHttpContextAccessor _contextAccessor;
		public LoginModel(SignInManager<ApplicationMember> signInManager, ILogger<LoginModel> logger, IHttpContextAccessor contextAccessor)
		{
			this.signInManager = signInManager;
			_logger = logger;
			_contextAccessor = contextAccessor;
		}
		public void OnGet()
		{
			if (_contextAccessor.HttpContext.Session.GetString("ModelError") != null)
			{
				ModelState.AddModelError("", _contextAccessor.HttpContext.Session.GetString("ModelError"));
			}
		}
		public bool ValidateCaptcha()
		{
			bool result = true;

			string captchaResponse = Request.Form["g-recaptcha-response"];

			HttpWebRequest req = (HttpWebRequest)WebRequest.Create
		   ("https://www.google.com/recaptcha/api/siteverify?secret=6Le7LlcpAAAAAPnzta0OWQS5tBqRLeECE0DUUtei &response=" + captchaResponse);


			try
			{

				using (WebResponse wResponse = req.GetResponse())
				{
					using (StreamReader readStream = new StreamReader(wResponse.GetResponseStream()))
					{

						string jsonResponse = readStream.ReadToEnd();

						myObject jsonObject = JsonConvert.DeserializeObject<myObject>(jsonResponse);

						result = Convert.ToBoolean(jsonObject.success);
					}
				}

				return result;
			}
			catch (WebException ex)
			{
				throw ex;
			}
		}

		public async Task<IActionResult> OnPostAsync(string submitButton)
			{
				if (ModelState.IsValid)
				{
					if (!ValidateCaptcha())
					{
						if (submitButton == "button1")
						{
							_contextAccessor.HttpContext.Session.SetString("Email",LModel.Email);
							return RedirectToPage("ForgetPassword");
						}
						else if (submitButton == "button2") {
							var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password, LModel.RememberMe, lockoutOnFailure: true);
							if (identityResult.Succeeded)
							{
								_contextAccessor.HttpContext.Session.Remove("ModelError");
								return RedirectToPage("TwoFactorEnabled");
							}
							else if (identityResult.IsLockedOut)
							{
								ModelState.AddModelError("", "Account has been locked out, please try again in 20 minutes");
							}
							else
							{
								ModelState.AddModelError("", "Username or password is incorrect");
							}
						}
					}
					else
					{
						ModelState.AddModelError("", "Captcha verification failed, please try again.");
					}
				}
				return Page();
			}
		}

	public class myObject
	{
		public string success { get; set; }
		public List<string> ErrorMessage { get; set; }
	}
}

Pages/Logout.cshtml.cs
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Session;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Assignment.Pages
{
    [Authorize]
    public class LogoutModel : PageModel
    {
		private readonly ILogger _logger;
		private readonly SignInManager<ApplicationMember> signInManager;
		private readonly IHttpContextAccessor _contextAccessor;
		private readonly AuthDbContext _context;
		public LogoutModel(AuthDbContext context, SignInManager<ApplicationMember> signInManager, IHttpContextAccessor httpContextAccessor, ILogger<LogoutModel> logger)
		{
			this.signInManager = signInManager;
			_contextAccessor = httpContextAccessor;
			_logger = logger;
			_context = context;
		}
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPostLogoutAsync()
		{
			_contextAccessor.HttpContext.Session.Clear();
			_contextAccessor.HttpContext.Session.Remove(".AspNetCore.Session");
			_contextAccessor.HttpContext.Session.Remove("AuthToken");
			_contextAccessor.HttpContext.Session.Clear();
			await _contextAccessor.HttpContext.Session.CommitAsync();
			if (Request.Cookies[".AspNetCore.Session"] != null)
			{
				_contextAccessor.HttpContext.Response.Cookies.Delete(".AspNetCore.Session");
			}
			if (Request.Cookies["AuthToken"] != null)
			{
				_contextAccessor.HttpContext.Response.Cookies.Delete("AuthToken");
			}
			var user = _context.Users.ToList().Where(member => member.Email == (User.FindFirstValue(ClaimTypes.Email))).FirstOrDefault();
			_context.AuditLogs.Add(new AuditLog
			{
				UserId = user.Id,
				ActivityDetails = "User has successfully logged out.",
				Timestamp = DateTime.Now,
			});
			user.SessionId = "";
			await _context.SaveChangesAsync();
			await signInManager.SignOutAsync();
			return RedirectToPage("Login");
		}
		public async Task<IActionResult> OnPostDontLogoutAsync()
		{
			return RedirectToPage("Homepage");
		}
	}
}

Pages/Register.cshtml.cs
using Assignment.Models;
using Assignment.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using System.Collections;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Web;

namespace Assignment.Pages
{
	[AutoValidateAntiforgeryToken]
	public class RegisterModel : PageModel
	{ 
		private UserManager<ApplicationMember> userManager { get; }
		private SignInManager<ApplicationMember> signInManager { get; }
		private readonly RoleManager<IdentityRole> roleManager;
		[BindProperty]
		public Register RModel { get; set; }
		private readonly IHttpContextAccessor _contextAccessor;
		private readonly AuthDbContext _context;
		public RegisterModel(UserManager<ApplicationMember> userManager,
		SignInManager<ApplicationMember> signInManager,
		RoleManager<IdentityRole> roleManager,
		IHttpContextAccessor httpContextAccessor,
		AuthDbContext context)
		{
			this.userManager = userManager;
			this.signInManager = signInManager;
			this.roleManager = roleManager;
			_contextAccessor = httpContextAccessor;
			_context = context;
		}
		public void OnGet()
		{
		}

		//Save data into the database
		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
				var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
				var protector = dataProtectionProvider.CreateProtector("HiddenWow");
				var user = new ApplicationMember()
				{
					UserName = RModel.Email,
					Email = RModel.Email,
					FirstName = RModel.FirstName,
					LastName = RModel.LastName,
					Gender = RModel.Gender,
					NRIC = protector.Protect(RModel.NRIC),
					DateOfBirth = RModel.DateOfBirth,
					Resume = RModel.Resume,
					WhoAmI = HttpUtility.HtmlEncode(RModel.WhoAmI)

				};

				//Create the Member role if NOT exist
				IdentityRole role = await roleManager.FindByIdAsync("Member");
				if (role == null)
				{
					await roleManager.CreateAsync(new IdentityRole("Member"));
				}

				var result = await userManager.CreateAsync(user, HttpUtility.HtmlEncode(RModel.Password));
				if (result.Succeeded)
				{
					string guid = Guid.NewGuid().ToString();
					_contextAccessor.HttpContext.Session.SetString("AuthToken", guid);
					_contextAccessor.HttpContext.Response.Cookies.Append("AuthToken", guid);
					var users = _context.Users.ToList().Where(member => member.Email == RModel.Email).FirstOrDefault();
					_context.AuditLogs.Add(new AuditLog
					{
						UserId = users.Id,
						ActivityDetails = "User has successfully signed up.",
						Timestamp = DateTime.Now,
					});
					user.MinimumPasswordAge = DateTime.Now.AddDays(1);
					user.MaximumPasswordAge = DateTime.Now.AddDays(120);
					await _context.SaveChangesAsync();
					result = await userManager.AddToRoleAsync(user, "Member");
					await signInManager.SignInAsync(user, false);
					return RedirectToPage("Homepage");
				}
				foreach (var error in result.Errors)
				{
					ModelState.AddModelError("", error.Description);
				}
			}
		return Page();
		}
	}
}

Pages/Admin.cshtml
@page
@model Assignment.Pages.AdminsModel
@{
    ViewData["Title"] = "Admin Page";
}

<h1>@ViewData["Title"]</h1>

<p>Welcome to the admin dashboard.</p>

Pages/ChangePassword.cshtml
@page
@model Assignment.Pages.ChangePasswordModel
@section Scripts{
	<script>
		function validate() {
			var score = 0
			var str = document.getElementById('password').value;
			var lbl = document.getElementById('passwordfeedback');
			var error = document.getElementById('clientsidevalidation')
			if (str.length >= 12) {
				score += 1
			}
			if (str.search(/[0-9]/) != -1) {
				score += 1
			}
			if (str.search(/[A-Z]/) != -1) {
				score += 1
			}
			if (str.search(/[a-z]/) != -1) {
				score += 1
			}
			if (str.search(/[^a-zA-Z0-9]/) != -1) {
				score += 1
			}
			if (score == 1) {
				lbl.innerHTML = "Very Weak!";
				lbl.style.color = "Red";
				error.innerHTML="Error"
			}
			if (score == 2) {
				lbl.innerHTML = "Weak!";
				lbl.style.color = "Red";
			}
			if (score == 3) {
				lbl.innerHTML = "Medium!";
				lbl.style.color = "Red";
			}
			if (score == 4) {
				lbl.innerHTML = "Strong!";
				lbl.style.color = "Red";
			}
			if (score == 5) {
				lbl.innerHTML = "Excellent!";
				lbl.style.color = "Blue";
			}
		}
	</script>
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div>
			<h1 class="mb-3">Change Password</h1>

			<br />

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label">Old Password</label>
					<input type="password" asp-for="oldPassword" class="form-control" />
				</div>

				<div class="mb-3">
					<div class="flex-row g-2">	
						<label class="form-label">New Password</label>
						<label style="margin-left:70%">Password Status: </label>
						<label id="passwordfeedback"></label>
					</diV>
					<input type="password" id="password" asp-for="Password" onkeyup="validate()" class="form-control" />
				</div>

				<div class="mb-3">
					<label class="form-label">Confirm Password</label>
					<input type="password" asp-for="confirmPassword" class="form-control" />
				</div>
				
				@Html.AntiForgeryToken()

				<div class="mb-3" style="margin-left:90%; margin-top:3%">
					<button type="submit" class="btn btn-primary">Register</button>
				</div>
			</form>
		</div>
	</div>
</div>

Pages/ForgetPassword.cshtml
@page
@model Assignment.Pages.ForgetPasswordModel
@{
}

<div class="d-flex justify-content-center align-items-center ">
    <h3>An email has been sent to you, please click on the link to reset your password</h3>
</div>

Pages/Homepage.cshtml
@page
@model Assignment.Pages.HomepageModel;
@{
}
<h1>User Details</h1>
<p>Email: @ViewData["Email"]</p>
<p>Name: @ViewData["FirstName"] @ViewData["LastName"]</p>
<p>Gender: @ViewData["Gender"]</p>
<p>NRIC: @ViewData["NRIC"]</p>
<p>Description: @ViewData["WhoAmI"]</p>
<p>Resume: @ViewData["Resume"]</p>
<form method="post">
<button type="submit" class="btn btn-primary">Change Password</button>
</form>

Pages/Index.cshtml
@page
@model IndexModel
@{
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is a web application to demonstrate the different security features implemented.</p>
</div>

Pages/Login.cshtml
@page
@model Assignment.Pages.LoginModel
@section Scripts
{
	<script src="https://www.google.com/recaptcha/api.js?render=6Le7LlcpAAAAAOv5i2tfqWXc85OGGZfYG0OBDhTL"></script>

	<script>
		grecaptcha.ready(function () {
				grecaptcha.execute('6Le7LlcpAAAAAOv5i2tfqWXc85OGGZfYG0OBDhTL', { action: 'Login' }).then(function (token) {
				document.getElementById("g-recaptcha-response").value = token;
			});
		});
	</script>
}

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<br />

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<button type="submit" name="submitButton" value="button1" style="margin-left:40%">Forget Passsword</button>
					<input type="password" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				@Html.AntiForgeryToken()

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>

					<button type="submit" name="submitButton" value="button2" class="btn btn-primary" style="margin-left:40%">
						Login
					</button>
				</div>
				<input type="hidden" id="g-recaptcha-response" name="g-recaptcha-reponse" />
			</form>
		</div>
	</div>
</div>

Pages/Logout.cshtml
@page
@model Assignment.Pages.LogoutModel
@{
}
<form method="post">
    <div class="container mt-5">
        <div class="d-flex flex-column justify-content-center align-items-center">
            <div>
                  <h1> Are you sure you want to logout? </h1>
            </div>
            <div class="d-flex flex-row justify-content-center align-items-center" style="margin-top:4%">
                <button class="btn btn-primary" style="margin-right:100%" asp-page-handler="Logout">Yes</button>
                <button class="btn btn-light border-dark" asp-page-handler="DontLogout">No</button>
            </div>
        </div>
    </div>
</form>

Pages/TwoFactorEnabled.cshtml
@page
@model Assignment.Pages.TwoFactorEnabledModel
@{
}


<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
		<form method="post">
			<div asp-validation-summary="All" class="text-danger"></div>

			<div class="mb-3">
				<label class="form-label">2 Factor Authentication</label>
				<input type="text" asp-for="userValue" class="form-control" />
			</div>

			@Html.AntiForgeryToken()

			<div class="mb-3" style="margin-left:70%; margin-top:3%">
				<button type="submit" class="btn btn-primary">Verify</button>
			</div>
		</form>
		</div>
	</div>
</div>